import type { ToolDefinition } from "./types";

const emptyParams = { type: "object", properties: {}, additionalProperties: false };

/**
 * Tool metadata — single source of truth for risk, routing, and OpenAI schemas.
 * Execution stays in execute-tool.ts; registry wraps with confirmation + standard results.
 */
export const TOOL_DEFINITIONS: ToolDefinition[] = [
  {
    name: "get_today_sales",
    description:
      "REQUIRED before sales or revenue questions. Returns latest uploaded report or a single day when the user names a date (e.g. July 8). Pass user_message so the date can be parsed.",
    category: "sales",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/sales",
    whenToUse:
      "User asks about sales, revenue, top products, stores, MHVR, uploaded CSV, or sales on a specific date (e.g. show sales of 8 July).",
    whenNotToUse: "Never guess sales numbers from memory.",
    examplePhrases: [
      "how are sales today",
      "top products",
      "show sales of 8 july",
      "sales on July 8",
    ],
    costNotes: "No LLM — reads local report.",
    parameters: {
      type: "object",
      properties: {
        focus: {
          type: "string",
          enum: ["top_store", "top_products", "summary", "full_report"],
          description:
            "top_store = best store; top_products = best SKUs by qty; summary = brief; full_report = complete breakdown",
        },
        user_message: {
          type: "string",
          description:
            "Original user question — used to infer focus and specific dates like '8 july'",
        },
        date: {
          type: "string",
          description: "Optional ISO date YYYY-MM-DD to filter the report to one day",
        },
      },
      additionalProperties: false,
    },
  },
  {
    name: "query_sales",
    description:
      "Universal Sales Intelligence. Filtered summaries, rankings, breakdowns by store/department/design/vendor/class, dates, and follow-up context. Prefer this over guessing. Pass user_message for NL parsing.",
    category: "sales",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/sales",
    whenToUse:
      "Novello/Ovani/LADYS RING/MHVR/14KT sales, by store/department, yesterday/kal, show filtered sales, top vendor models with filters.",
    whenNotToUse:
      "Never invent numbers. For unusual statistical correlations use open_data_analyst.",
    examplePhrases: [
      "Show Novello sales",
      "Novello ki kal ki sales batao",
      "LADYS RING by vendor",
      "now by department",
    ],
    costNotes: "Deterministic — reads loaded report only.",
    parameters: {
      type: "object",
      properties: {
        user_message: { type: "string", description: "Original user question" },
        designs: { type: "array", items: { type: "string" } },
        departments: { type: "array", items: { type: "string" } },
        stores: { type: "array", items: { type: "string" } },
        vendors: { type: "array", items: { type: "string" } },
        classes: { type: "array", items: { type: "string" } },
        groupBy: {
          type: "array",
          items: {
            type: "string",
            enum: [
              "date",
              "store",
              "department",
              "design",
              "vendor",
              "class",
              "product",
              "sku",
              "vendor_model",
            ],
          },
        },
        date_type: {
          type: "string",
          enum: [
            "today",
            "yesterday",
            "this_week",
            "last_week",
            "this_month",
            "last_month",
            "all_dates",
            "custom",
          ],
        },
        start_date: { type: "string" },
        end_date: { type: "string" },
        navigate: { type: "boolean", description: "Open Sales dashboard with filters" },
        limit: { type: "number" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "compare_sales",
    description:
      "Compare two stores, designs, departments, vendors, or classes using the loaded sales report.",
    category: "sales",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/sales",
    whenToUse: "Compare Great Mall and Valley Fair, Novello vs Ovani, LADYS RING vs GENTS RING.",
    whenNotToUse: "Single-entity summaries use query_sales.",
    examplePhrases: ["Compare Great Mall and Valley Fair", "Novello vs Ovani"],
    parameters: {
      type: "object",
      properties: {
        user_message: { type: "string" },
        left: { type: "string" },
        right: { type: "string" },
        entity_type: {
          type: "string",
          enum: ["store", "department", "design", "vendor", "class", "product"],
        },
        navigate: { type: "boolean" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_sales_entity_details",
    description:
      "Detail panel data for one store/department/design/vendor/class — same depth as Sales dashboard drawer.",
    category: "sales",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/sales",
    whenToUse: "Open MHVR details, show LADYS RING details, store detail breakdown.",
    whenNotToUse: "Broad rankings use query_sales.",
    examplePhrases: ["Show MHVR details", "Open LADYS RING on Sales"],
    parameters: {
      type: "object",
      properties: {
        user_message: { type: "string" },
        entity_type: {
          type: "string",
          enum: ["store", "department", "design", "vendor", "class", "product"],
        },
        entity_name: { type: "string" },
        navigate: { type: "boolean" },
      },
      required: ["entity_type", "entity_name"],
      additionalProperties: false,
    },
  },
  {
    name: "get_top_vendor_models",
    description: "Top vendor models by revenue or quantity with optional filters.",
    category: "sales",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/sales",
    whenToUse: "Top vendor models for MHVR, top Novello models, highest revenue product.",
    whenNotToUse: "Never invent SKUs.",
    examplePhrases: ["Show top vendor models for MHVR", "top Novello models"],
    parameters: {
      type: "object",
      properties: {
        user_message: { type: "string" },
        vendors: { type: "array", items: { type: "string" } },
        designs: { type: "array", items: { type: "string" } },
        departments: { type: "array", items: { type: "string" } },
        stores: { type: "array", items: { type: "string" } },
        sort_by: { type: "string", enum: ["revenue", "quantity"] },
        limit: { type: "number" },
        navigate: { type: "boolean" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "apply_sales_dashboard_filters",
    description: "Apply filters on the Sales dashboard and navigate to /sales.",
    category: "sales",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/sales",
    whenToUse: "User says show/open on Sales dashboard with current or named filters.",
    whenNotToUse: "When they only want a spoken/text answer with no UI.",
    examplePhrases: ["Open Novello on Sales dashboard", "show this on sales"],
    parameters: {
      type: "object",
      properties: {
        user_message: { type: "string" },
        designs: { type: "array", items: { type: "string" } },
        departments: { type: "array", items: { type: "string" } },
        stores: { type: "array", items: { type: "string" } },
        vendors: { type: "array", items: { type: "string" } },
        classes: { type: "array", items: { type: "string" } },
        date: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_sales_snapshot",
    description: "Return a compact Sales Dashboard snapshot summary (KPIs, top rankings, freshness).",
    category: "sales",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    whenToUse: "High-level dashboard overview, what is on sales right now.",
    whenNotToUse: "For filtered custom questions use query_sales.",
    examplePhrases: ["sales dashboard overview", "what's on the sales snapshot"],
    parameters: emptyParams,
  },
  {
    name: "get_sales_data_status",
    description: "Return active sales data version, freshness, source file, and date coverage.",
    category: "sales",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    whenToUse: "Is sales data up to date? What date does the report cover?",
    whenNotToUse: "For actual sales numbers use query_sales.",
    examplePhrases: ["is sales data refreshed", "through what date is the report"],
    parameters: emptyParams,
  },
  {
    name: "get_sales_insights",
    description: "Return deterministic sales insights (top/weak performers, discount and margin opportunities).",
    category: "sales",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    whenToUse: "Which stores/vendors are weak? High discount? Low margin?",
    whenNotToUse: "Do not invent insights — only from the snapshot engine.",
    examplePhrases: ["which vendor had high sales but low margin", "sales opportunities"],
    parameters: {
      type: "object",
      properties: {
        user_message: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "refresh_sales_data",
    description: "Rebuild the versioned sales snapshot from the latest uploaded report. Requires confirmation.",
    category: "sales",
    riskLevel: "confirmation_required",
    requiresConfirmation: true,
    allowedInVoice: true,
    allowedInChat: true,
    whenToUse: "User explicitly asks to refresh sales data.",
    whenNotToUse: "Never refresh on ambiguous requests.",
    examplePhrases: ["refresh sales data", "rebuild sales snapshot"],
    parameters: {
      type: "object",
      properties: {
        force: { type: "boolean" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_email_summary",
    description: "REQUIRED before inbox or unread mail questions.",
    category: "email",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/email",
    whenToUse: "Inbox summary, unread count, urgent emails.",
    whenNotToUse: "Do not read full email bodies unless user asked.",
    examplePhrases: ["summarize my inbox", "any urgent emails"],
    parameters: emptyParams,
  },
  {
    name: "get_calendar_today",
    description: "REQUIRED before calendar or schedule questions for today.",
    category: "calendar",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/calendar",
    whenToUse: "Today's meetings, schedule, appointments.",
    whenNotToUse: "Never invent meetings.",
    examplePhrases: ["what's on my calendar", "meetings today"],
    parameters: emptyParams,
  },
  {
    name: "list_tasks",
    description: "List pending tasks and reminders.",
    category: "tasks",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    whenToUse: "Task list, to-do, what do I need to do.",
    whenNotToUse: "For adding tasks use add_task.",
    examplePhrases: ["my tasks", "what's on my to-do list"],
    parameters: emptyParams,
  },
  {
    name: "list_contacts",
    description: "Find contacts or phone numbers.",
    category: "contacts",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/contacts",
    whenToUse: "Contact lookup by name.",
    whenNotToUse: "Do not invent phone numbers.",
    examplePhrases: ["find Ross contact", "Lisa's phone number"],
    parameters: {
      type: "object",
      properties: { query: { type: "string" } },
      additionalProperties: false,
    },
  },
  {
    name: "search_company_knowledge",
    description: "Search Valliani company knowledge: policies, brands, founder. NOT for store addresses or distances.",
    category: "knowledge",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    whenToUse: "Company facts, return policy, brands, founder.",
    whenNotToUse: "For store addresses, phone, nearest store, or distances use get_store_directory or find_nearest_store.",
    examplePhrases: ["return policy", "who founded valliani"],
    parameters: {
      type: "object",
      properties: { query: { type: "string" } },
      required: ["query"],
      additionalProperties: false,
    },
  },
  {
    name: "get_store_directory",
    description: "REQUIRED for store listings, addresses, phone, hours, city/state lookups. Uses synced official directory — never guess.",
    category: "stores",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    whenToUse: "Store list by state/city, address, phone, hours, call a store.",
    whenNotToUse: "For distance/nearest store use find_nearest_store.",
    examplePhrases: ["stores in California", "address of Great Mall", "call Ontario Mills"],
    parameters: {
      type: "object",
      properties: {
        user_message: { type: "string", description: "Original user question" },
        query: { type: "string", description: "Store/mall/city/state to look up" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "find_nearest_store",
    description: "REQUIRED for nearest/closest store questions. Uses Haversine on synced coordinates — never invent distance.",
    category: "stores",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    whenToUse: "Nearest or closest store to a mall, city, or location.",
    whenNotToUse: "If coordinates missing, explain needsGeocoding — do not guess distance.",
    examplePhrases: ["nearest store to Great Mall", "closest branch to Valley Fair"],
    parameters: {
      type: "object",
      properties: {
        storeName: { type: "string", description: "Mall or store name" },
        city: { type: "string" },
        state: { type: "string" },
        limit: { type: "number", description: "1-3 nearest stores", minimum: 1, maximum: 3 },
        user_message: { type: "string", description: "Original user question" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "list_valliani_stores",
    description: "List Valliani stores by state, city, region, or status from official store directory JSON.",
    category: "stores",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    whenToUse: "Show all Texas stores, stores in San Jose, stores opening soon.",
    whenNotToUse: "For nearest distance use find_nearest_store.",
    examplePhrases: ["show all Texas stores", "which stores are opening soon"],
    parameters: {
      type: "object",
      properties: {
        state: { type: "string" },
        city: { type: "string" },
        region: { type: "string" },
        status: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_valliani_store_details",
    description: "Get one store's address, phone, hours and metadata from official JSON directory.",
    category: "stores",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    whenToUse: "Phone/address/hours for Great Mall, Valley Fair, Ontario Mills.",
    whenNotToUse: "For nearest distance use find_nearest_store.",
    examplePhrases: ["what is Great Mall phone number", "address of Valley Fair"],
    parameters: {
      type: "object",
      properties: {
        id: { type: "string" },
        storeName: { type: "string" },
        city: { type: "string" },
        query: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_instagram_account",
    description:
      "Get the Instagram Business profile: username, name, follower count, media count. Live from Meta Graph API.",
    category: "social",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/social",
    whenToUse: "Instagram followers, profile, account stats, how many followers.",
    whenNotToUse: "For post lists use get_instagram_recent_posts.",
    examplePhrases: ["how many Instagram followers", "show my Instagram account"],
    parameters: emptyParams,
  },
  {
    name: "get_instagram_recent_posts",
    description: "List recent Instagram posts with caption, type, likes, comments count, and permalink.",
    category: "social",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/social",
    whenToUse: "Latest Instagram posts, recent content, how posts are doing.",
    whenNotToUse: "For a single post's comments use get_instagram_post_comments.",
    examplePhrases: ["show latest Instagram posts", "recent posts"],
    parameters: {
      type: "object",
      properties: { limit: { type: "number", minimum: 1, maximum: 25 } },
      additionalProperties: false,
    },
  },
  {
    name: "get_instagram_post_comments",
    description: "Get latest comments for a specific Instagram post by mediaId.",
    category: "social",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/social",
    whenToUse: "Comments on a post, what people are saying on latest post.",
    whenNotToUse: "Without a mediaId, first fetch posts with get_instagram_recent_posts.",
    examplePhrases: ["show comments on latest post", "comments on this post"],
    parameters: {
      type: "object",
      properties: { mediaId: { type: "string", description: "Instagram media/post id" } },
      required: ["mediaId"],
      additionalProperties: false,
    },
  },
  {
    name: "get_instagram_post_insights",
    description: "Get performance insights (reach, impressions, engagement, saves) for a post by mediaId.",
    category: "social",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/social",
    whenToUse: "How a post performed, reach, impressions, engagement of a post.",
    whenNotToUse: "Some media types have no insights — surface the graceful message.",
    examplePhrases: ["how did my last post perform", "reach of this post"],
    parameters: {
      type: "object",
      properties: { mediaId: { type: "string", description: "Instagram media/post id" } },
      required: ["mediaId"],
      additionalProperties: false,
    },
  },
  {
    name: "open_social_dashboard",
    description: "Open the Social section (Instagram Business dashboard).",
    category: "social",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/social",
    whenToUse: "Open social, go to Instagram dashboard.",
    whenNotToUse: "For data answers use the specific get_instagram_* tools.",
    examplePhrases: ["open social", "go to Instagram dashboard"],
    parameters: emptyParams,
  },
  {
    name: "draft_instagram_caption",
    description: "Draft Instagram caption variations for a topic. DRAFT ONLY — never publishes.",
    category: "social",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/social",
    whenToUse: "Write/draft a caption for a post or product.",
    whenNotToUse: "Publishing is not enabled — only produce drafts.",
    examplePhrases: ["draft a caption for a gold necklace post", "write an Instagram caption"],
    parameters: {
      type: "object",
      properties: { topic: { type: "string", description: "What the post is about" } },
      required: ["topic"],
      additionalProperties: false,
    },
  },
  {
    name: "draft_instagram_comment_reply",
    description: "Draft a courteous reply to an Instagram comment. DRAFT ONLY — never replies automatically.",
    category: "social",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/social",
    whenToUse: "Draft a reply to a specific comment.",
    whenNotToUse: "Auto-reply is not enabled — only produce drafts.",
    examplePhrases: ["draft a reply to this comment", "reply to the comment"],
    parameters: {
      type: "object",
      properties: {
        comment: { type: "string", description: "The comment text to reply to" },
        commenter: { type: "string", description: "Commenter username, if known" },
      },
      required: ["comment"],
      additionalProperties: false,
    },
  },
  {
    name: "get_instagram_inbox",
    description:
      "List Instagram DM conversations (people who messaged the business account) with last snippet and unread count. Requires instagram_manage_messages permission.",
    category: "social",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/social",
    whenToUse: "Instagram DMs, inbox, who messaged me, unread Instagram messages.",
    whenNotToUse: "Follower lists are not available via the API.",
    examplePhrases: ["show my Instagram DMs", "who messaged me on Instagram"],
    parameters: emptyParams,
  },
  {
    name: "get_instagram_conversation",
    description: "Get message history for one Instagram DM conversation by conversationId.",
    category: "social",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/social",
    whenToUse: "Read messages in a specific Instagram thread.",
    whenNotToUse: "Without a conversationId, first call get_instagram_inbox.",
    examplePhrases: ["show messages in this conversation", "read this Instagram thread"],
    parameters: {
      type: "object",
      properties: { conversationId: { type: "string" } },
      required: ["conversationId"],
      additionalProperties: false,
    },
  },
  {
    name: "draft_instagram_dm",
    description: "Draft a reply to an Instagram DM. DRAFT ONLY — never sends without confirmation.",
    category: "social",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/social",
    whenToUse: "Draft a reply to an Instagram direct message.",
    whenNotToUse: "Auto-sending is not enabled — only produce drafts for review in the UI.",
    examplePhrases: ["draft a reply to this DM", "reply to this Instagram message"],
    parameters: {
      type: "object",
      properties: {
        to: { type: "string", description: "Recipient username or id" },
        message: { type: "string", description: "The incoming message being replied to (for tone/context)" },
        intent: { type: "string", description: "What the reply should convey" },
      },
      required: ["message"],
      additionalProperties: false,
    },
  },
  {
    name: "get_metal_rates",
    description: "Gold and silver prices per gram.",
    category: "calculator",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/calculator",
    whenToUse: "Gold price, silver price, metal rates.",
    whenNotToUse: "For jewelry quote use estimate_jewellery_price.",
    examplePhrases: ["gold price", "silver rate"],
    parameters: emptyParams,
  },
  {
    name: "estimate_jewellery_price",
    description: "Estimate jewelry price from weight and karat.",
    category: "calculator",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/calculator",
    whenToUse: "Price quote for X grams gold.",
    whenNotToUse: "Not for live spot-only questions.",
    examplePhrases: ["how much for 10 grams 22k gold"],
    parameters: {
      type: "object",
      properties: {
        weight_grams: { type: "number" },
        karat: { type: "string", enum: ["24K", "22K", "18K", "14K"] },
        metal: { type: "string", enum: ["gold", "silver"] },
        making_percent: { type: "number" },
        tax_percent: { type: "number" },
      },
      required: ["weight_grams"],
      additionalProperties: false,
    },
  },
  {
    name: "get_industry_news",
    description: "Jewelry and metals industry headlines.",
    category: "news",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/news",
    whenToUse: "Industry jewelry news.",
    whenNotToUse: "Sports/politics have separate tools.",
    examplePhrases: ["jewelry news", "industry headlines"],
    parameters: emptyParams,
  },
  {
    name: "get_sports_news",
    description: "Sports headlines.",
    category: "news",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/news",
    whenToUse: "Sports news requests.",
    whenNotToUse: "Industry news uses get_industry_news.",
    examplePhrases: ["sports news", "MLB scores"],
    parameters: emptyParams,
  },
  {
    name: "get_politics_news",
    description: "Politics and world news headlines.",
    category: "news",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/news",
    whenToUse: "Politics or world news.",
    whenNotToUse: "Industry news uses get_industry_news.",
    examplePhrases: ["politics news", "world headlines"],
    parameters: emptyParams,
  },
  {
    name: "add_task",
    description: "Add a new task or reminder.",
    category: "tasks",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/calendar",
    whenToUse: "Remind me, add task.",
    whenNotToUse: "Removing tasks uses delete_task.",
    examplePhrases: ["remind me to call vendor Friday"],
    parameters: {
      type: "object",
      properties: {
        title: { type: "string" },
        due_date: { type: "string" },
        due_time: { type: "string" },
        priority: { type: "string", enum: ["low", "medium", "high"] },
        description: { type: "string" },
      },
      required: ["title", "due_date"],
      additionalProperties: false,
    },
  },
  {
    name: "delete_task",
    description: "Remove/delete a task by name.",
    category: "tasks",
    riskLevel: "dangerous",
    requiresConfirmation: true,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/calendar",
    whenToUse: "User wants to delete/remove/cancel a task.",
    whenNotToUse: "Never delete without confirmation.",
    examplePhrases: ["delete the vendor follow-up task"],
    parameters: {
      type: "object",
      properties: {
        title: { type: "string" },
        task_id: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "complete_task",
    description: "Mark a task as done.",
    category: "tasks",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    whenToUse: "Mark task complete/done.",
    whenNotToUse: "Deleting uses delete_task.",
    examplePhrases: ["mark vendor call as done"],
    parameters: {
      type: "object",
      properties: {
        title: { type: "string" },
        task_id: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "add_meeting",
    description: "Schedule a calendar meeting.",
    category: "calendar",
    riskLevel: "confirmation_required",
    requiresConfirmation: true,
    allowedInVoice: true,
    allowedInChat: false,
    opensPage: "/calendar",
    whenToUse: "Schedule/add meeting with time.",
    whenNotToUse: "Requires confirmation when user preference enabled.",
    examplePhrases: ["schedule meeting with Lisa Friday 3pm"],
    parameters: {
      type: "object",
      properties: {
        title: { type: "string" },
        start: { type: "string" },
        end: { type: "string" },
        location: { type: "string" },
        attendees: { type: "array", items: { type: "string" } },
        user_message: { type: "string", description: "Natural-language meeting request if start not provided" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "delete_meeting",
    description: "Cancel or remove a calendar meeting.",
    category: "calendar",
    riskLevel: "dangerous",
    requiresConfirmation: true,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/calendar",
    whenToUse: "Cancel/delete meeting. Must identify exact event.",
    whenNotToUse: "Always requires confirmation.",
    examplePhrases: ["cancel the 3 PM meeting", "delete store review meeting"],
    parameters: {
      type: "object",
      properties: {
        title: { type: "string" },
        event_id: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "delete_all_meetings",
    description: "Remove all meetings from the calendar. Requires explicit confirmation.",
    category: "calendar",
    riskLevel: "dangerous",
    requiresConfirmation: true,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/calendar",
    whenToUse: "User wants to clear/delete/remove all calendar events or everything from calendar.",
    whenNotToUse: "Single meeting delete — use delete_meeting.",
    examplePhrases: ["remove everything from calendar", "delete all meetings"],
    parameters: {
      type: "object",
      properties: {
        delete_all: { type: "boolean" },
        event_ids: { type: "array", items: { type: "string" } },
      },
      additionalProperties: false,
    },
  },
  {
    name: "draft_email_reply",
    description: "Draft email reply to important inbox email.",
    category: "email",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/chat",
    whenToUse: "Draft/reply to email. Safe to draft; never sends.",
    whenNotToUse: "Sending requires propose_send_email + confirm.",
    examplePhrases: ["draft a reply", "reply politely"],
    parameters: emptyParams,
  },
  {
    name: "open_data_analyst",
    description: "Data Analyst — summarize latest uploaded report or open for custom CSV queries.",
    category: "navigation",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/analyst",
    whenToUse: "Analyze CSV, report breakdown, top products in report, analyst page.",
    whenNotToUse: "Simple live sales snapshot uses get_today_sales.",
    examplePhrases: ["open data analyst", "analyze my sales CSV", "top products in the report"],
    parameters: {
      type: "object",
      properties: {
        user_message: { type: "string", description: "Original question for report context" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_settings_status",
    description: "Integration status: Google, Plaid, News API, confirmation preferences.",
    category: "navigation",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    opensPage: "/settings",
    whenToUse: "Settings, integrations, is Google connected, connection status.",
    whenNotToUse: "For live inbox use get_email_summary.",
    examplePhrases: ["is Google connected", "open settings", "integration status"],
    parameters: emptyParams,
  },
  {
    name: "generate_jewellery_image",
    description: "Generate AI jewelry product image.",
    category: "media",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: false,
    opensPage: "/images",
    whenToUse: "Create/generate jewelry image from description.",
    whenNotToUse: "Uses Gemini — not for text-only questions.",
    examplePhrases: ["generate a gold bridal necklace"],
    parameters: {
      type: "object",
      properties: { prompt: { type: "string" } },
      required: ["prompt"],
      additionalProperties: false,
    },
  },
  {
    name: "show_detail_page",
    description:
      "Navigate to an app section. Speak ONLY 'Opening {Section}.' — never summarize on open.",
    category: "navigation",
    riskLevel: "safe",
    requiresConfirmation: false,
    allowedInVoice: true,
    allowedInChat: true,
    whenToUse:
      "User says open/go to/take me to a section (Sales Today, News and Markets, Email, etc.).",
    whenNotToUse: "Prefer specific tools when user wants data not navigation.",
    examplePhrases: [
      "open sales today",
      "open news and markets",
      "go to email",
      "open price calculator",
    ],
    parameters: {
      type: "object",
      properties: {
        page: {
          type: "string",
          enum: [
            "sales",
            "calendar",
            "email",
            "chat",
            "contacts",
            "images",
            "news",
            "analyst",
            "calculator",
            "stores",
            "settings",
            "social",
          ],
        },
      },
      required: ["page"],
      additionalProperties: false,
    },
  },
];

export const TOOL_BY_NAME = new Map(TOOL_DEFINITIONS.map((t) => [t.name, t]));
